site_name: Learn Python
site_url: https://gbilgi.github.io/learn-python/
repo_url: https://github.com/gbilgi/learn-python

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy

markdown_extensions:
  - admonition
  - tables
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - "1. Basics":
      - Introduction: 01-basics/introduction.md
      - Installation: 01-basics/installation.md
      - Basic Fundamentals of Python: 01-basics/python-fundamentals.md
  - "2. Core Syntax":
      - Print Function: 02-core-syntax/print-function.md
      - Operators in Python: 02-core-syntax/operators.md
      - Control Flow: 02-core-syntax/control-flow.md
      - Loops in Python: 02-core-syntax/loops.md
  - "3. Data Structures":
      - Strings in Python: 03-data-structures/strings.md
      - Lists: 03-data-structures/lists.md
      - Tuples: 03-data-structures/tuples.md
      - Dictionary: 03-data-structures/dictionaries.md
      - Sets: 03-data-structures/sets.md
  - "4. Functions & OOP":
      - Functions: 04-functions-and-oop/functions.md
      - OOP in Python: 04-functions-and-oop/oop.md
  - "5. Practical Skills":
      - File Handling in Python: 05-practical-skills/file-handling.md
      - Error & Exception Handling: 05-practical-skills/errors-and-exceptions.md
  - Cheatsheet: cheatsheet.md
  - Glossary: glossary.md
  - Resources: resources.md
